### ISSUE TITLE
Ps3 OFW 4.82 (CECH-2503B)

### ISSUE THREAD

**Issue by JantsoP** [littlebalup/PyPS3tools#15]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2246637/dump.hex.checklog.txt)

Only one warning and it was ROS1
`Following check(s) returned a WARNING!
  009.05   ROS1 Hash`

Is it safe to put in CFW or do I just use it w/o CFW?

**Comment by littlebalup** [comment]
Same answer than this : https://github.com/littlebalup/PyPS3tools/issues/14

Your console is not compatible for CFW! You'll brick! Do not reboot!
Write back to original data before to reboot using that flash file instead of the one provided with Ps3xploit : https://www.dropbox.com/s/j375d0ku1mz3alx/PSXploit_v2%20-%20flash%20reverter.zip?dl=1
It's your only chance to not brick.

**Comment by JantsoP** [comment]
It's interesting because I restarted console many times + installed REBUG REX CFW w/o any issues.

**Comment by littlebalup** [comment]
The log you sent is from a CECHC-300x. So... maybe the wrong log.

**Comment by JantsoP** [comment]
Huh.

So it seems that I gave the wrong log file.
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2251242/dump.hex.checklog.txt)

This is the correct one :)

**Comment by xRifles** [comment]
Did this work for you in the end? I have a 2501A console which can be downgraded to 3.40 and im getting the exact same log error

**Comment by JantsoP** [comment]
> Did this work for you in the end? I have a 2501A console which can be downgraded to 3.40 and im getting the exact same log error

Actually I did. I don't remember what I did but I got it working.
I have faint memory of just trial and error.... i think.
