### ISSUE TITLE
SKU Identification

### ISSUE THREAD

**Issue by Maverick5555** [littlebalup/PyPS3tools#41]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/7018489/dump.hex.checklog.txt)

not sure what this error means. am i still able to jailbreak. using CFW 4.88.2 evilnat cobra 8.3?

cheers

**Comment by Maverick5555** [comment]
my md5's do match up

**Comment by littlebalup** [comment]
That's not an error but a warning.
That "WARNING: NOR dump must be patched with 4.xx Patchset to install CFW on this machine!" means that machine can't be patched with the legacy 3.55 patches. Because your console is 3.56 minimum firmware.

So, you can jailbreak it using the PS3 Toolset or hardware flasher that use 4.xx (no-fsm) patches. But you can't downgrade to 3.55.

**Comment by Maverick5555** [comment]
Okay cool thanks for the response :)

What do I miss out on not being able to go to 3.55? sorry for the questions new to the ps3 scene

**Comment by littlebalup** [comment]
Not many things. It was useful in the past to access the FSM but there are other methods now.

**Comment by Maverick5555** [comment]
Legend thanks mate
