### ISSUE TITLE
Matching SKU : WARNING!    No matching SKU found! (With checklog and model #)

### ISSUE THREAD

**Issue by MattysMasquerades** [littlebalup/PyPS3tools#79]
[PS3FlashDump491OFW.bin.checklog.txt](https://github.com/user-attachments/files/16433898/PS3FlashDump491OFW.bin.checklog.txt)

Model CECHH01

**Comment by bchr** [comment]
> [PyPS3checker.changelog.txt](https://github.com/user-attachments/files/16277132/PyPS3checker.changelog.txt)
> 
> Model CECHH01

Looks like you uploaded the wrong file.

**Comment by MattysMasquerades** [comment]
> > [PyPS3checker.changelog.txt](https://github.com/user-attachments/files/16277132/PyPS3checker.changelog.txt)
> > Model CECHH01
> 
> Looks like you uploaded the wrong file.

Whoops! Just changed it.

I installed HEN anyway since, but I didn't proceed with CFW.

**Comment by littlebalup** [comment]
>******* Getting SKU identification datas *******
  idps = 0x06
  metldr0 = 0xE920
  metldr1 = 0x0E8E
  metldrkey = 0x99873BC715F280809C302225
  bootldr0 = 0x2F4B
  bootldr1 = 0x2F4B
  bootldrsize = 0x2F4F0

>  Matching SKU : WARNING!
   No matching SKU found!

This warning means SKU identification data does not match regular data for your model referenced here https://github.com/littlebalup/PyPS3tools/blob/a00d3f6c785bc0b2a5dd2e9a0d114c244d9eff48/PyPS3checker/checklist.xml#L2128

This may be due to altered idps or, in your case, because it's a refurbished console.

> ******* Additional information *******
HDD : ST1000LM048-2E7172 ZKP2PQZ4
MAC address : 28:0D:FC:BC:00:78
CID : **0x0FFF001C54C3**
eCID : 01CD0055C11C47180C0F6C4000000000
board_id (part of console S/N) : 27435655
kiban_id (board barcode) : 3LD00460303F
**This is a refurbished console!**

Not a big deal, your console is ok. But you are warned it's not regular machine.
